[workspace]
authors = ["Surya Prakash <surya0prakash@proton.me>"]
channels = ["conda-forge"]
name = "papers"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.3.5,<3"
pandas = ">=2.3.3,<3"
matplotlib = ">=3.10.8,<4"
scipy = ">=1.16.3,<2"
requests = ">=2.32.5,<3"
